spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: mallservice
  datasource:
    username: guest
    password: ${MYSQL_PASSWORD:dev}
    url: jdbc:mysql://localhost/test_spring_cloud?serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
  redis:
    host: localhost
    port: 6379
    database: 2
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100ms
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka

server:
  port: 8360

mybatis-plus:
  mapper-locations: mybatis-mapper/*.xml

---
spring:
  profiles: pro
  datasource:
    username: guest
    password: ${MYSQL_PASSWORD:pro}
    url: jdbc:mysql://lz-mysql/test_spring_cloud?serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: lz-redis
    port: 6379
    database: 2
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100ms

server:
  port: 8081

mybatis-plus:
  mapper-locations: mybatis-mapper/*.xml